### ISSUE TITLE
Compatibility with Craft 3.4

### ISSUE THREAD

**Issue by bencroker** [fruitstudios/craft-searchit#22]
With the redesigned UI in Craft 3.4, the Searchit plugin is broken. Specifically, the `_elements/indexcontainer` template has been renamed to `_elements/toolbar`, likely along with some other changes. 

Renaming the template fixes the issue, however the layout needs some adjusting.

![Screenshot 2020-01-06 at 15 23 22](https://user-images.githubusercontent.com/57572400/71823866-8ef7fb00-3098-11ea-8d80-7af05d529b27.png)

This is with Craft 3.4.beta-5

**Comment by samhibberd** [comment]
Thanks for reporting @bencroker

**Comment by verbeeksteven** [comment]
@samhibberd any update?

**Comment by verbeeksteven** [comment]
Looks like it was fixed in CraftCMS (https://github.com/craftcms/cms/commit/043a24f339e319f489cee15c8b6025772587e5c9) though it is deprecated and should be fixed

**Comment by bencarr** [comment]
In Craft 3.4, the element index layout also [removed the `toolbar` and `elementindex` classes](https://github.com/craftcms/cms/commit/83d27a36a922a5d357b92f939110aef3c180585b#diff-6cd1fe09430aea4ccb957ac2f298b1ec), so Searchit's CSS for the Max Filter Width and Compact Mode settings no longer applies.

**Comment by johndwells** [comment]
Posting to subscribe to this. Currently still an issue with 3.4.11. Really hope to see this fixed soon.

**Comment by brettburwell** [comment]
Add me to the list of folks excited to see a fix for this.

**Comment by brettburwell** [comment]
p.s. For anyone looking for a quick and partial fix, you can use the excellent [Control Panel CSS plugin](https://plugins.craftcms.com/cp-css) to apply a max-width to Searchit's select menu (which was my primary issue). 

Here's the CSS in case it's helpful to anyone else:
```
.searchit--filters select {
  max-width: 120px;
}
```

**Comment by bencroker** [comment]
I've been using my own fork which works great with Craft 3.4.x. Just submitted a PR, but for anyone who wants to get it right away, add this to your `composer.json`:

```
  "require": {
    "fruitstudios/searchit": "dev-master",
```

and 

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/bencroker/craft-searchit"
    }
  ]
```

Then run `composer update`.
